### ISSUE TITLE
AttributeError: 'AnalogSignalArray' object has no attribute '_data'

### ISSUE THREAD

**Issue by pietromarchesi** [kemerelab/UncoveringTemporalStructureHippocampus#2]
Hi, 

Thanks for sharing the notebooks. I am trying to run them, however, the code breaks because of the missing `_data` attribute. A simple example:

```python
import nelpy as nel

datadirs = ['data/']
fileroot = next( (dir for dir in datadirs if os.path.isdir(dir)), None)

if fileroot is None:
    raise FileNotFoundError('datadir not found')

load_from_nel = True

if load_from_nel:
    jar = nel.load_pkl(fileroot + 'fig1.nel')
    exp_data = jar.exp_data
    aux_data = jar.aux_data
    del jar

print(exp_data)

```

Fails with: 

```
Traceback (most recent call last):
  File "/home/pietro/Envs/basic36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-35-1adcaa0a1d8f>", line 22, in <module>
    print(exp_data)
  File "/home/pietro/Envs/basic36/lib/python3.6/site-packages/nelpy/core/_analogsignalarray.py", line 1053, in __repr__
    if self.isempty:
  File "/home/pietro/Envs/basic36/lib/python3.6/site-packages/nelpy/core/_analogsignalarray.py", line 1917, in __getattr__
    return object.__getattribute__(self, name)
  File "/home/pietro/Envs/basic36/lib/python3.6/site-packages/nelpy/core/_analogsignalarray.py", line 1194, in isempty
    return self.data.shape[1] == 0
  File "/home/pietro/Envs/basic36/lib/python3.6/site-packages/nelpy/core/_analogsignalarray.py", line 1917, in __getattr__
    return object.__getattribute__(self, name)
  File "/home/pietro/Envs/basic36/lib/python3.6/site-packages/nelpy/core/_analogsignalarray.py", line 1104, in data
    return self._data
  File "/home/pietro/Envs/basic36/lib/python3.6/site-packages/nelpy/core/_analogsignalarray.py", line 1917, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'AnalogSignalArray' object has no attribute '_data'
```

Essentially, nothing inside `exp_data` seems to have this `_data` attribute and so it breaks everywhere.

**Comment by pietromarchesi** [comment]
__Update:__
It seems to be more general than the `_data` attribute, running 
```python
aux_data['16-40-19']['short']['PBEs_noIN'].unit_ids
```
fails with
```
AttributeError: 'BinnedSpikeTrainArray' object has no attribute '_series_ids'
```
Could this have something to do with how the files were pickled / are being unpickled?

**Comment by eackermann** [comment]
Hi Pietro, thanks for pointing this out.

I'll look into it a bit more deeply soon, but here are a couple of things to note:

The eLife version of the nelpy code and data are working together, so if you clone that version of nelpy (https://github.com/elifesciences-publications/nelpy) then things should work as expected.

However, since then I've made several improvements to nelpy, including making the internals a bit more consistent and flexible, which has caused this missing `_data` attribute to show up. But this particular issue has at least been fixed (AFAIK) here https://github.com/nelpy/nelpy/commit/9ff2bbc0336cd6af8b1dd437022a3582b4bf2625

So, (1) if you just want to get it up and running quickly, simply use the eLife fork to run these notebooks; (2) if you update to the latest version of nelpy (either with git pull, or pip upgrade), I actually *think* that it should work as well, since I have added code to deal with the backwards compatibility issue.

However, I haven't fully tested (2) on these notebooks, so I will do so when I have time, and I will then update these notebooks and perhaps the data format as well to bring it up to parity with the latest version of nelpy.

**Comment by eackermann** [comment]
> **Update:**
> It seems to be more general than the `_data` attribute, running
> 
> ```python
> aux_data['16-40-19']['short']['PBEs_noIN'].unit_ids
> ```
> 
> fails with
> 
> ```
> AttributeError: 'BinnedSpikeTrainArray' object has no attribute '_series_ids'
> ```
> Could this have something to do with how the files were pickled / are being unpickled?

This is definitely a version issue: nelpy version when data was pickled was like the one hosted on eLife (https://github.com/elifesciences-publications/nelpy), whereas you are using a much newer version of nelpy.

I think the updated version of nelpy should work for the AnalogSignalArrays just fine, but looking more carefully, I don't have that auto-upgrade functionality built in everywhere, so I expect some things to fail. Again, for now, probably using the older nelpy fork with the older data is your best bet, but I will update the data format and notebooks here to make it work with the current version, and I'll update here.

Making data future-proof is always challenging, but I'm working on a way to avoid this similar issue in the future.

**Comment by pietromarchesi** [comment]
Hi Etienne, 

Thanks for your reply. Indeed it was a version issue, and installing the old Nelpy works fine. I will stick to the old Nelpy to mess around a bit with the notebooks, and move to the newer release afterwards. Cheers!

P
